FROM node:20

# Install build dependencies
RUN apt-get update && \
    apt-get install -y libxtst-dev

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install npm dependencies
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose port (adjust as needed)
EXPOSE 3000

# Start your application
CMD ["npm", "start"]
  